segmentio/nightmare

.gitignore
Readme.md
lib/actions.js
test/index.js

adding new resourceRequestStarted event for executing in phantomjs context, with updated docs and test

---

package.json
test/fixtures/evaluation/index.html
test/fixtures/events/index.html
test/fixtures/manipulation/index.html
test/fixtures/manipulation/result.html
test/fixtures/manipulation/results.html
test/fixtures/navigation/a.html
test/fixtures/navigation/b.html
test/fixtures/navigation/c.html
test/fixtures/navigation/index.html
test/fixtures/options/index.html
test/fixtures/simple/index.html
test/fixtures/upload/index.html
test/index.js
test/mocha.opts
test/server.js

Huge internal change for the tests. Rather than relying on production sites like google/yahoo/wikipedia/etc, this replaces those tests with a local server. (using some static fixtures)
Tests should run a lot faster, and won't break when live sites change. (while still testing the exact same functionality)

fixing tests by using a local server and static fixtures

---

Readme.md

Here it is: https://github.com/h2non/nightmare-google-oauth2
That's all

Add google-oauth2 plugin to readme

---

lib/actions.js
test/fixtures/manipulation/index.html
test/index.js

added 'mouseover'

---

test/index.js

Fix test with missing nightmare.end(), fix #232

---

Readme.md
lib/actions.js
lib/runner.js

Great work guys.  I switched over to the atom editor in May and have been impressed with the stability of atom-shell (now electron).  Nice choice of dependencies for browser automation!
Cheers!

Resurrect .useragent api from v1, b275ff0.

---

package.json
test/index.js

`after` and `util` are not used in test/index.js.

Remove after and util in test/index.js

---

lib/javascript.js
lib/preload.js
lib/runner.js
test/fixtures/rendering/index.html
test/index.js

~~Sorry for the extra field in package.json & a missing semicolon, but I think they could be fixed with the next bump clean~~ (cleaned) ;) fix #247 #242

Use node-integration for electron, fix #247 & amd scripts loading

---

test/index.js

changing the tests to point to github to avoid the great firewall

---

lib/actions.js
test/index.js

The pdf method should accept options (based on the documentation). I fixed the method to really accept them.
Fixes #264

Adding options to pdf method

---

lib/actions.js

`self` is not used in `waitms`

Remove unnecessary variable

---

Readme.md

Add a comment about the `co-mocha` package, fixes #261

Mention co-mocha package for examples

---

lib/actions.js

Remove old evaluate method, fix #257

---

Readme.md
package.json
test/mocha.opts

Seems to be more performant, leaner, and has better error handling. Solves #279

Replace co-mocha w/ mocha-generators

---

package.json

add `npm test` command since that's really common when people clone a project :)
koa and metalsmith do same thing

set make test as the npm test target

---

Readme.md
lib/actions.js
test/fixtures/manipulation/index.html
test/index.js

Added a ```mousedown``` event to fulfill enhancement #201.

enhancement: added mousedown event

---

Readme.md
lib/actions.js
lib/nightmare.js
test/index.js

In Nightmare v1 there was an option to timeout .wait(), i added this back in to v2
please don't merge both of this pull requests https://github.com/segmentio/nightmare/pull/305  at the same time, they will have conflicts.
I can merge the other with upstream/origin and update the other after you have merged one of this.

Timeout wait

---

Readme.md
lib/nightmare.js
lib/preload.js
lib/runner.js
test/index.js

Sets up the `page-alert` event for alerts, preventing alerts from blocking the process.  Should fix #359.  Thoughts? /cc @yoz

alert events

---

test/fixtures/manipulation/index.html
test/index.js

It makes the TODO in the scroll test done.

"manipulation" fixture fixed to correctly test horizontal scrolling

---

Readme.md
test/fixtures/preload/index.html
test/fixtures/preload/index.js
test/index.js

Add information and a test on how to add your own custom preload script

Custom preload script

---

lib/actions.js
lib/runner.js
test/fixtures/manipulation/index.html
test/index.js

This PR updates `nightmare.type()` to use the native send input command and trigger the right events.

use native electron sendInputEvent for nightmare.type(...)

---

Readme.md
lib/actions.js
test/index.js

clear input on falsey/empty values

---

Readme.md

Was going through the documentation and noticed a missing #. Will come up with a better PR next time.
Cheers!

Added a missing # to Readme

---

Readme.md
lib/actions.js
test/index.js

added ability to uncheck

---

lib/actions.js
test/index.js

now properly fails with integer wait time

---

lib/actions.js
lib/runner.js
test/index.js

Added ability to return buffer from pdf

---

Readme.md
lib/nightmare.js

fixes: #442 
bug introduced by: #438

added default waitTimout

---

Readme.md

added debugging flags to README

---

lib/runner.js

See http://blog.atom.io/2015/11/17/electron-api-changes.html

Update use of electron APIs to kill deprecation warnings for 1.0

---

Readme.md
lib/runner.js

Fixes (or at least shows) an example of how to address #505.

added `openDevTools` to Nightmare options

---

Readme.md
lib/actions.js
lib/runner.js
test/index.js

Electron now supports basic authentication : https://github.com/atom/electron/pull/3250
This PR adds an `.authentication()` method to Nightmare.

Add authentication

---

lib/actions.js
test/index.js

Should capture error if evaluate fn is not a function.

---

package.json
test/index.js

`devTools` test, electron version bump

---

Readme.md

Using a room pointed at my fork as an interim solution until Segment can fix separation of internal/external concerns.  Fixes #272.

Add Gitter badge

---

Readme.md

documentation touchups about headers

---

lib/actions.js

wait(selector) comment touchup

---

Readme.md
lib/actions.js
lib/nightmare.js
lib/runner.js
test/index.js

Quick attempt to address #599.

adds `.engineVersions()` to the API

---

Readme.md
example.js

2 changes:
1) Made the example script shown in the readme.md to actually be the
content of example.js (fix the existing mismtach)
2) small correction to be able to run the example directly after install
(at least on windows) by including the 'node_module\nightmare' as part
of the path and changing yahoo.js to example.js

Adjusted example script and readme file

---

Readme.md
lib/nightmare.js
test/index.js

add `.once()` and `.removeListener()`

---

package.json

Upgrade to Electron 1.2.1

---

lib/nightmare.js
test/files/nightmare-created.js
test/index.js

adding check for process when ending

---

Readme.md

Add useful information found in issue #665 for devs looking for proxy info.

Update proxy info

---

Readme.md

Up-to-date way to use preload scripts in README

---

Readme.md
lib/actions.js
lib/nightmare.js
test/index.js

Fixes #450.  Also serves as an excuse to clean up the `self` and `self.options` references.

adding poll option, cleaning up options

---

lib/runner.js
test/index.js

gracefully end when electron instance is closed

---

Readme.md
lib/actions.js
lib/runner.js
test/index.js

add `.cookies.clearAll()`

---

Readme.md

I should have paid closer attention to 721: it broke the link to CircleCI.  Fixing.

fixing badge link

---

lib/actions.js
test/index.js

modified:   lib/actions.js
* map .wait(selector, timeout)->args[1] to this.options.waitTimeout if typeof === 'number'

Fixes segmentio/nightmare#742 - .wait(element, timeout) implementation

---

Readme.md

touches up readme for .end()

---

lib/actions.js

Fixes ReferenceError when called in Strict Mode.
see issue #799

799 - Fixed wait() on Strict Mode

---

Readme.md

This adds a document for [mouseover(selector)](https://github.com/segmentio/nightmare/blob/2c3284723bc5c7d82a64ac8130af3b84774e4d54/lib/actions.js#L126-L137).

Add a document for mouseover(selector)

---

Readme.md

correct "demostrates" typo to "demonstrates"

---

Readme.md
lib/nightmare.js
test/index.js

Adds an api to forcibly kill the child process immediately, as discussed here: https://gitter.im/rosshinkley/nightmare?at=57d17dcb68f483b41cb0491a

Add .halt api

---

Readme.md
lib/nightmare.js
package.json
test/index.js

upgrading to electron 1.4.4

---

Readme.md

making documentation explicit about error-first callbacks

---

Readme.md

action parent function only takes one argument
Fixes https://github.com/segmentio/nightmare/issues/897

update README to reflect correct signatures

---

Readme.md
lib/actions.js
test/fixtures/manipulation/index.html
test/index.js

There's a `mousedown`, but no `mouseup`!? This changes that ;)

Add `mouseup` action (ready to merge)

---

Readme.md
lib/nightmare.js
test/index.js

`.end(fn)` should use `.then()`

---

Readme.md

Yahoo.com's home page took a very long time to work—for a moment I thought nightmare.js wasn't working!

Readme: update example to use duckduckgo.com

---

lib/javascript.js

This might be a good fix for any site that has issues with the code injection.
Fix for #791

Fix for #791 __nightmare is undefined on wellsfargo.com

---

Readme.md

Seems like #865 took out these lines (sorry, my fault)

Readme: make example actually work

---

Readme.md

previous link is 404, replace it with correct link address

replace the 404 link with valid link

---

Readme.md

adding link to How to run nightmare on Amazon Linux guide

---

Readme.md

update wrong example

---

Readme.md

Fix link to electron events documentation

Closes segmentio/nightmare#975 - Link to Electron events-documentation broken. #975

---

lib/actions.js

This sets the mouse position of all the mouse events to be the center of the element that you interact with (currently it defaults to (0, 0)).

Set mouse position for mouse events

---

lib/preload.js
lib/runner.js

Fix error on preload

---

.eslintrc.js
Makefile
example.js
lib/actions.js
lib/frame-manager.js
lib/ipc.js
lib/javascript.js
lib/nightmare.js
lib/preload.js
lib/runner.js
package.json
test/index.js
test/server.js
yarn.lock

This PR modernizes the release of nightmare a bit and should cut down on some issues and PRs. 
Here's what's changed:
- Added the recommended linting via eslint (e.g. `eslint:recommended`)
- Added prettier formatting (prettier with single quotes and no semicolons)
- Install from an exact yarn version to avoid npm regressions like this (https://github.com/npm/npm/issues/17161)
- Added a git pre-commit hook via husky to run `make test` before each commit
Closes #1215

chore: add linting, formatting, consistent package management (via yarn) and a precommit hook
