Readme.md, lib/actions.js, lib/index.js, test/index.js
We have a service that is running nightmare as part of it's API. If the PhantomJS process dies unexpectedly, the `phantom` lib will throw an **[uncaught exception](https://github.com/sgentle/phantomjs-node/blob/2645246eb987b163b233cc042715bd0a6a4d181f/phantom.coffee#L91-L92)**. As is the case with uncaught exceptions, this crashes the entire server. Thankfully, `phantom` does expose an [`onExit` option/hook](https://github.com/sgentle/phantomjs-node/blob/2645246eb987b163b233cc042715bd0a6a4d181f/phantom.coffee#L88-L89) that allows you to handle such cases.
As far as nightmare is concerned, this adds a new custom event. (ie: `Nightmare#on('exit', ...);`) When this handler is attached, it will be called upon with the given exit `code` and `signal`. (the signal is not always present, but in …
=> Handling Phantom crashes more gracefully

lib/actions.js, package.json, test/fixtures/navigation/index.html, test/index.js
Fixes this error: 
```
phantom stdout: SyntaxError: DOM Exception 12: An invalid or illegal string was specified.
```
when trying to use escaped selectors (e.g. `.wait("#escaping\\:test")`)
=> Fix escaping of selectors in .wait(selector)

lib/actions.js
@t-suwa proposed this fix in #179, just creating a PR for easy merging.
I'm running into this problem on CircleCI. Their artifacts directories have extra periods in them, and this currently breaks any use of `screenshot()` when trying to save to them.
=> Fix screenshot() for paths with 2+ periods (#179)

package.json, test/index.js
Cuts the test suite's running time from 2m to 1m on my machine. I've been using it with nightmare-driven test suites, as well as a module that subclasses it. Figured it might be helpful. :)
=> Speed up test suite with mocha.parallel

lib/nightmare.js
When I run `make test`, it threw `Cannot read property 'apply' of undefined`.
Now it checks if done is passed as an argument.
Another fix for the if could be:
~~~js
if (done) {
return this.run(done)
}
~~~
Because as I understand, `done` is only passed if nightmare is not running ?
=> fix end() if no done passed as argument

lib/actions.js, lib/runner.js
fixed up the `nightmare.screenshot(path)` implementation. Basically passes the image buffer back from the electron process to the node process to write the file.
Here's an example:
```js
var Nightmare = require('./')
Nightmare()
.goto('https://google.com')
.screenshot('screenshot.png')
.end(function(err) {
if (err) throw err
})
```
=> implement screenshots

lib/ipc.js
A non connected node process in the IPC emitter would cause electron to
break.
=> Fix electron errors casued by process not connected

lib/runner.js, test/fixtures/options/index.html, test/index.js
In trying to turn off cross origin policy using  `web-preferences: {web-security: false}` as specified in [Electrons options](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions), I realized it hoses nightmare's use of the `web-preferences` setting. 
This PR fixes it.   Tests included.   It also provides a v2-compatible solution for https://github.com/segmentio/nightmare/issues/203.
=> Allow for user-specified web-preferences options.

test/index.js
The test case of 'type and click' doesn't ensure 'type' works
'type and click' passes even when 'type' types nothing
=> Add test case for 'type'

Readme.md, lib/nightmare.js, lib/preload.js, lib/runner.js, test/fixtures/events/index.html, test/index.js
There are two ways of getting an exception in Nightmare, one is to inject some "bad" code via .evaluate(), this will stop nightmare and even call done() in mocha. But there is also the issue with already existing code, that has errors, now there is an option to listen for this.
Same with console log, before only console logs from evaluate() where shown.
=> Excetions and console.logs now have event callbacks

Readme.md
In the README documentation menu, the URL for **Set up a new instance** was [wrong](https://github.com/segmentio/nightmare#new-nightmareoptions).
This pull request changes it to a [correct](https://github.com/segmentio/nightmare#nightmareoptions) one.
It started from the commit https://github.com/segmentio/nightmare/commit/562e7e42d98d8e844883ae7f7c79e8722ca287e6,  when it removed the **new** keyword but missed the respective URL hash.
I hope I didn't mess anything.
=> Fix menu sub-section URL in documentation

Readme.md
The documentation in Electron's master branch differs from the documentation for the version of Electron Nightmare is on.  As such, the link in the Nightmare constructor should point to the versioned documentation.
=> point to versioned Electron documentation

lib/runner.js
The formerly used "did-finish-load" is not always emitted after an action
in case webContents.isLoading() is true. Thus the "continue" event is never
emitted. The probability of this behavior rises with rising frequency
of actions, resulting in flaky behavior and hangs depending on the
target site.
The electron documentation states that "did-finish-load" is only
dispatched when the "onload" event is dispatched and the spinner of the
tab has stopped spinning. Yet the "onload" event is not always dispatched
when webContents.isLoading() is true. Therfore the correct event is
"did-stop-loading" which is always dispatched after isLoading()
transitions to false.
=> Use "did-stop-loading" event in "continue"

test/index.js
Hey Nightmare Team - it looks like mocha test suite isn't automatically initializing `mocha-generators` so the tests only appear to run and succeed, instead of running.
**Branch**: Master
**Commit**: 748a2b2b14163d34e89108250e34553d991e7913
Modify any test to have a `console.log` - never logs to console.
Setup needs `require('mocha-generators').install()`
=> Initialize mocha-generators so tests run

Readme.md, lib/nightmare.js, lib/runner.js
This is useful for example to change the userData directory so you don't reuse cookies and such from other instances.
=> Allow overriding Electron app paths

Readme.md, lib/actions.js, test/index.js
I've got a use case for the screenshot function that doesn't require it to be written to disk. Electron itself returns the image in memory, so I thought it'd be useful if writing it to the disk were optional. This pull request maintains backwards compatibility and adds the necessary tests. These tests actually pass (https://github.com/segmentio/nightmare/pull/290), but I didn't include the line from that PR to avoid a conflict.
=> Return a buffered screenshot if no path is provided

Readme.md, lib/actions.js, test/index.js
=> Allow passing arguments to wait(fn), just like evaluate()

test/index.js
For test passing on small screen resolution.
Because on some platforms electron can not set initial viewport size more than screen resolution.
=> Viewport size changed in the 'should set viewport' test

lib/nightmare.js, lib/runner.js, package.json, test/index.js, test/server.js
Adds a headers() method to override headers for all requests from that instance of nightmare.
``` javascript
yield nightmare
.headers({ 'X-Nightmare-Header': 'hello world' })
.goto('localhost:3000/');
```
And adds an optional param to goto(), specifying headers to use for that specific request:
``` javascript
yield nightmare
.goto('localhost:3000/', { 'X-Nightmare-Header': 'hello world' });
```
Fixes #325
=> Add headers() method, and optional headers param to goto()

Readme.md, lib/actions.js, lib/nightmare.js, lib/runner.js, package.json, test/fixtures/cookies/index.html, test/index.js
Adds support for getting and setting cookies. Originally, I wanted to just export `.cookie(...)` (as discussed in #241), but electron has a lot of power to query all the cookies or query for certain cookies on urls. I didn't want to intentionally limit their API. 
I decided to use sub-properties because it's going to get messy if we have a ton of top-level methods, so instead of:
```js
nightmare.setCookie(...)
nightmare.getCookie(...)
```
It looks like:
```js
nightmare.cookies.get(...)
nightmare.cookies.set(...)
```
This should allow for more powerful namespacing for things like `sessions`, `cache`, `proxy`, etc.
---
Additionally, while putting this together, I improved error handling. If the main electron process encounters an uncaughtException, it will propagate to the node process …
=> add nightmare.cookies.get(...) and nightmare.cookies.set(...) support

Readme.md, lib/actions.js, lib/nightmare.js, test/index.js
With this change, Nightmare now supports both `nightmare.use(plugin)` and `Nightmare.action(name, action | namespace)`
Originally I thought we could combine them, but they actually do two different things. `action` extends the prototype and ensures that the action is properly queued. `use` is helpful for re-using and abstracting out tasks you want to perform on nightmare.
=> added: Nightmare.action(name, action | namespace) and nightmare.use(plugin)

lib/nightmare.js, test/index.js
=> Fixed 'args is not defined' error for paths option

Readme.md
I've noticed that you're bundling `0.35.2` which includes additional options for `printToPDF`, including additional paper sizes like `letter`, `A5` etc. 
The current documentation points to an older version of Electron docs which do not show all possible settings. This PR updates the link to reference the docs specifically for `0.35.2`
=> PDF Options Out of Date

test/mocha.opts
mocha-generators is now required in `test/index.js` explicitly.
=> Removed useless mocha opt

lib/runner.js, test/index.js
Option naming of `BrowserWindow` was changed at Electron v0.35. (e.g. `max-width` -> `maxWidth`)
Documentation:
https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions
=> Followed new BrowserWindow option naming

Readme.md, lib/preload.js, lib/runner.js, package.json, test/index.js
**BREAKING:** changed `page-error`, `page-alert`, and `page-log` to `nightmare.on("page", function (type, ... ))`
it allows you to hook into the following console events:
- console.log
- console.warn
- console.error
and the following window events:
- alert
- prompt
- confirm
This PR also prevents prompts, alerts, and confirms from freezing the process while emitting events for each.
=> add events for prompt, alert, confirm, and the other console events

Readme.md, lib/nightmare.js, test/index.js
I added `electronPath` option to options of `Nightmare()`.
I added this because I want to use Nightmare for end-to-end Electron app testing (e.g. Nightmare uses Electron v0.35.2 but my app uses new API introduced on Electron v0.35.4).  Nightmare now fixes Electron version.  I agree that it's reasonable bacause Nightmare can't support all versions of Electron.  So I added notation to document.
=> Added 'electronPath' option to customize Electron path

lib/nightmare.js
if you spin up 10 nightmare processes, you get nasty console messages about an event emitter leak because 10+ listeners will be attached to process. this tells node everything is okay and we meant to do this.
=> fix eventemitter leak message

Readme.md, lib/nightmare.js, lib/runner.js, test/index.js
Support [Chrome command line switches](https://github.com/atom/electron/blob/master/docs/api/chrome-command-line-switches.md) (e.g. proxy-server, ignore-certificate-errors).
=> Support Chrome command line switches

lib/runner.js, test/index.js
Fix being able to construct nightmare with user defined paths. The electron method takes 2 arguments instead of 1.
=> fix setting electron paths

lib/runner.js
Hiding the application dock icon gives a more polished experience and
abstracts the user from Nightmare's internals.
I believe this was commented out by mistake.
=> Uncomment OS X dock hide

Readme.md, lib/nightmare.js, lib/runner.js
The dock icon is now hidden by default by the following pull request:
https://github.com/segmentio/nightmare/pull/426
This OS X specific option allows the dock icon to be shown again, mainly
for testing purposes, and makes no harm in other operating systems.
Fixes: https://github.com/segmentio/nightmare/issues/377
=> Implement dock option

lib/nightmare.js
=> page event listener fix

lib/nightmare.js, test/index.js
If a wait function times out and throws an error with functions queued up (i.e. the wait function is not the last step in a chain of actions) execution should fail immediately, yielding the error that was thrown.
If anything else is missing from this PR let me know and I'll be happy to address. Thanks for all the hard work that has gone into this project, it's a pleasure to use!
It seems like the following GitHub issues are related:
https://github.com/segmentio/nightmare/issues/397
https://github.com/segmentio/nightmare/issues/171
=> Fix failed wait with queued up functions

lib/runner.js
this electron flag seems to stop the fullscreen context switching described in #434
=> should fix fullscren swiching

Readme.md
Fixes #490, addresses @Mr0grog's comments from #482.  Also removes `vo` from the CNN example based on [@matthewmueller's comment](https://github.com/segmentio/nightmare/pull/482#issuecomment-184525044).
That being said: why the move to excise `vo`?  Is it to remove the external dependency?  I still think showing an example of using `vo` or `co` with `yield` is helpful.  Thoughts?
=> Yahoo example, vo removal

lib/nightmare.js, test/files/nightmare-unended.js, test/index.js
If the process Nightmare is running in exits or is killed (via a graceful process.exit() call, interrupt signal, etc), this ensures that the underlying Electron process Nightmare is managing also gets closed and cleaned up so users don't have have tons of rogue Electrons running.
Fixes #474.
=> Kill electron process when Nightmare's process exits/dies

Readme.md
=> Fix a typo in Readme

lib/nightmare.js
Yesterday, I ran up against #224, and before finding all of the helpful info there (_thank you everyone_), I was doing my own debugging based on the [exit code](http://tldp.org/LDP/abs/html/exitcodes.html) of the electron child process. This should hopefully make it easier to identify potential issues when ["it just quits."](https://github.com/segmentio/nightmare/issues/224#issuecomment-177268035)
If you're seeing exit code 127, you may not have electron installed correctly.
If you're seeing exit code 126, you may not have all the necessary dependencies for electron (:wave: gtk).
If you're seeing exit code 1, xvfb is a likely suspect in my experience.
If you're seeing exit code 0, electron appears to be working fine and it's something else.
Do you agree the exit code is helpful when …
=> add debug to inspect how electron exited

lib/actions.js
Previously if you had multiple instances of nightmare spun up and all using .wait() they would all share a single waitTimeout counter. This resulted in some elements firing incorrectly and others not firing when they should. Instead the waitTimeout value has been attached to the nightmare instance which also makes it observable. Alternatively you could create a closure but I think this is nicer.
=> Fixes multiple instances of nightmare using the same waitTimeout value

test/index.js
This makes sure the Nightmare browser session in cookie tests uses a temporary in-memory store so that it doesn't pick up cookies from other runs of nightmare (not a problem in CI because it's a clean environment every time, but a big help when developing locally). Ran into this while working on #468 because some of the cookie tests were failing right off the bat for me!
=> Ensure cookies are not shared across tests

lib/javascript.js, test/fixtures/events/index.html, test/index.js
Currently, `on('console', function() {})` cannot catch `console.log` event when it is called in `nightmare.click(selector)`.
I guess nightmare injects wrong `ipc.send` for `console.log` at `lib/javascript.js`.
nightmare injects an event for `console.log` at `lib/preload.js` already. So the injecting at `lib/javascript.js`  seems to be unnecessary.
Additionally, it doesn't match the interface in between `lib/preload.js` and `lib/javascript.js`.
https://github.com/segmentio/nightmare/blob/master/lib/preload.js#L14
=> Fix inject an event for console.log

Readme.md, lib/actions.js, lib/runner.js, test/index.js
This works very similar to the screenshot or pdf actions, except it saves the page as html to disk. Its a pretty straight forward pass through to the corresponding electron api.
=> Add an html action

lib/frame-manager.js, lib/runner.js, package.json, test/index.js
This is meant to address #468.
The basic gist of the change is to add a `FrameManager` object that emits events whenever the browsers renders a new frame and use that to figure out when to call `capturePage()`.
Some notes:
- At current, this can trigger pretty massive memory consumption. Due to a bug in Electron (https://github.com/atom/electron/issues/4441), trying to unsubscribe from frames can cause a crash (and there's no way to know whether that will happen ahead of time and smartly wait until it's safe). That means that, once we start subscribing, we don't stop until the window is closed (i.e. until nightmare's `end()` method is called).
For reference, a really simple nightmare session takes 20-30 MB of RAM on my machine, but once a screenshot is taken, that can boost to as high as …
=> Synchronize screenshots using frame subscription API

lib/nightmare.js, test/files/nightmare-error.js, test/index.js
Nightmare adds an `uncaughtException` listener to clean up the child process. However adding a listener [overrides the default behaviour](https://nodejs.org/docs/latest/api/process.html#process_event_uncaughtexception) and can cause an exit code of zero.
```js
// a.js
var Nightmare = require("nightmare");
var n = Nightmare();
var a = require("does-not-exist");
```
And then running `node a.js; echo $?` show the error but reports an exit code of `0`.
Re-throw the error so node can pick it back up. I also changed the `console.log` to a `debug` as the default handler prints a stack trace.
=> Pass uncaughtExceptions back to the default handler after cleanup

lib/frame-manager.js, test/index.js
Turns out I missed a condition on event subscription in Frame Manager that caused it to always automatically subscribe to frames upon instantiation, dramatically increasing overhead. This should fix that.
(Noticed while working on #553; I think this could be causing the slowdowns and test timeouts there, or at least exacerbating them.)
=> Don't subscribe to frames until there are actual listeners for frame data

Makefile, Readme.md, test/bb-xvfb, test/waitForX
Changes the makefile to run tests under an `xfvb` wrapper called `bb-xvfb` under one or more the following conditions:
* `make test` is executed on CircleCI.
* `make test` is executed on a box where `xvfb` is running.
* `make test` is executed in an environment where the `HEADLESS` variable is set and not equal to `1`.
(Disclaimer: my ability with GNU Make is pitiful, any pointers on how to make the Makefile better would be appreciated.)
The wrapper enforces starting `xvfb`, waiting for an X server to be ready, followed by starting `dbus` for IPC messaging, followed by your command.  In the case of `make test`, the unit tests are executed.
The original problem is explained in [Chromium bug 309093](https://bugs.chromium.org/p/chromium/issues/detail?id=309093), and I found that the …
=> run tests under an `xvfb` wrapper when headless

Readme.md, lib/nightmare.js, lib/runner.js, package.json, test/fixtures/navigation/invalid-frame.html, test/fixtures/navigation/invalid-image.html, test/fixtures/navigation/valid-frame.html, test/index.js, test/server.js
~~**This is just a work-in-progress at the moment, but filing the PR as there are open questions…**~~
This adds tests (which fail), but no implementation—I need to work out the best solution for https://github.com/atom/electron/issues/5013 and https://github.com/atom/electron/issues/4396 (this second one I can’t actually reproduce, so it may have been fixed). For the former, the simplest solution is probably tracking the URL of the failed page and comparing it to the URL of the main frame. Need to make sure that works right for redirects, though. A more exacting solution might be to track resource requests on the `session` object, though doing so requires a bit more rigamarole.
There is also an open question of how this should behave w/r/t error responses (e.g. 404, 500, etc). For now, …
=> Goto should fail if the page doesn’t load

lib/preload.js, lib/runner.js, test/index.js
We were using a few deprecated Electron APIs in various spots. Best to fix that before they disappear entirely and break! Happily, they were all just renamings or moves to other locations, so this was very straightforward.
Noticed while looking at #421.
=> Fix usage of deprecated Electron APIs

package.json, test/index.js
Running across #581 made me think it would be a good idea to get automatic warning of deprecated API usage. This causes the test suite to fail at the end if any deprecated APIs are used.
The implementation basically wraps the Nightmare constructor used in tests and watches Electron’s `stderr` for deprecation warnings, then throws an exception at the end if there were any.
=> Add testing for deprecated API usage in Electron

lib/actions.js
I was inspired to do this because some event listeners e.g. 'change' are triggered on blur, so they don't happen until we actually click/focus another element.
P.S. insert and type are very similar - there's some potential for refactoring but I don't know what style we would prefer.
=> blur text inputs when finished with type() or insert()

lib/runner.js, test/index.js
Electron has a potential crasher (on OS X, at least) when the devtools are open: https://github.com/electron/electron/issues/5180
This is an extremely simple workaround. Nightmare’s event forwarding code sends the `event.sender` argument, which may contain properties that crash Electron when accessed. Nightmare triggers the crash by stringifying everything when forwarding the event across IPC. This simply avoid including the `sender`.
I *think* it would be nicer not to send the `event` object at all (since this patch leaves it as an empty object in most cases and I don’t think it provided any users with useful data), but I am ever so slightly worried that changing which arguments are where in the events could bite somebody. This seemed safer.
=> Workaround for Electron event sender crash

lib/nightmare.js, package.json
Fixes #421, at least in part.
Open questions: 
1. Should Nightmare override the environment variable for `ELECTRON_ENABLE_LOGGING`?
2. Should the `nightmare:` namespace be on the debug calls for Electron?
=> piping electron stdout and stderr to debug calls

lib/actions.js, package.json, test/index.js
=> test nonexistent selectors for `.type()` and `.insert()`, change exceptions to use `chai-as-promised`

package.json
Contains upstream fixes for #375, #563, #572. For the dev tools issues, I think we should still take #576, but this does obviate it on a technical level.
=> Upgrade to Electron 0.37.7

lib/nightmare.js
This is one of several issues @fr- noted in #282. It is also important because the registered listener could cause the Nightmare instance to be retained even if there are no other references to it, which means instances can never be garbage collected.
This also removes the uncaught exception listener on the parent process, as mentioned in https://github.com/segmentio/nightmare/issues/586#issuecomment-212681749.
Finally, ensure the instance gets marked as ended even if the child process connection has already died (e.g. it crashed).
Other notes:
- This adds a “private” variable to nightmare instances named `_endNow`. I’d like not to do that, but nightmare already stores several private variables this way and I didn’t want to either totally rearrange the code by bringing `run` inside a …
=> Remove `process` event listeners when a Nightmare instance ends

lib/runner.js, test/index.js
Fixes #590.
We used to support `javascript:` URLs, but lost that feature in #553. TBH, I’m slightly skeptical on bringing it back, *but* #553 got released in an extra-minor update, so it seems worth fixing since it actually broke some people.
Bonus: this supports page loading data for URLs like `javascript:window.location='http://google.com'`. It could be ever so slightly faster if we didn’t bother to support that. Seemed nice to have, though. ¯\\\_(ツ)\_/¯
Also worth noting: we don’t handle errors especially well this way. It’s not any worse than before, but I wonder if calling `goto('javascript:notAnActualFunction()')` should return error instead of success, which I think we could do by passing JS URLs through the evaluate code and then, if the result is not `undefined`, setting the URL. …
=> Bring back support for `javascript:` URLs

Readme.md, lib/actions.js, lib/ipc.js, lib/nightmare.js, lib/runner.js, test/index.js
This addresses one aspect of #493. It should make IPC between the user’s process and the Electron process a) “safe” in that simultaneous calls can’t cause incorrect results and b) simpler. It’s based on discussion with @rosshinkley in issue #493.
The main idea here is that Nightmare’s IPC objects gain two methods, each to be used in opposite processes:
- `ipc.respondTo(name, responder)` Registers a function that can respond to calls from another process. The `name` is a handle by which other processes call it. The responder takes any number of arguments, where the last one is a callback. This callback should be called when the responder’s work is complete. Any arguments will be passed back to the caller in the other process. In addition, the callback has a method named `progress` that can …
=> Callback-based IPC

Readme.md
Hopefully this makes the README example a little more robust agains the regular, surface-level changes in Yahoo’s homepage.
=> Add catch clause and improve selectors in Yahoo example

lib/runner.js
Given notes on https://github.com/segmentio/nightmare/issues/602#issuecomment-215139708 and #607, it seems prudent to add a more explicit failure case for starting the Electron process with incorrect arguments.
*We should never hit this error,* but obviously it’s possible somehow. This at least helps make it more explicit what happened instead of getting some crazy error about trying to access the `dock` property. When people *do* hit it, it also might give some tiny bit of insight into exactly what happened.
=> Fail explicitly and with better messaging for wrong runner arguments

lib/nightmare.js, test/index.js
It felt very awkward to be able to use `.then`, but not `.catch` directly, leading me to write code like this:
```js
browser.evaluate(checkErrors).then(x => x).catch(err => {
// ...
})
```
This pr will allow me to skip the `.then(x => x)` part and just use `catch` directly, making it work even more as a normal promise.
```js
browser.evaluate(checkErrors).catch(err => {
// ...
})
```
=> Add catch function to nightmare instance

lib/runner.js
This fixes a potential bug where, if `goto('javascript:blahblahblah')` was called while a child frame was loading, the nightmare could wind up getting stuck, never moving on to the next action (because the `goto` machinery is only paying attention to events on the main frame).
[There's a related check for `isLoading()` in the `continue` action](https://github.com/segmentio/nightmare/blob/master/lib/runner.js#L459), but I figured that one was best to leave alone for now—if you want to take a screenshot, for example, you might want to make sure child frames have finished loading first. We could get a minor potential speed boost on pages with frames by changing it, though.
=> Javascript: URLs should only wait if the *main* frame is loading.

test/fixtures/preload/index.js
We fixed this in the actual preload script, but missed the test! This doesn’t upgrade Electron, but it is a prerequisite for upgrading. (The API is gone entirely in Electron 1.0)
=> Fix deprecated API usage in preload test (needed to support Electron 1.0+)

lib/runner.js, test/index.js
Fixes #642.
Ultimately, I think it would be better to reject with an instance of `TypeError` (with the same message), but that requires properly serializing and deserializing errors over IPC, which is a non-trivial task (would love to hear your thoughts on this, @rosshinkley). I wanted to get the immediate problem solved first.
=> Make `goto` reject w/ a helpful message when `url` is not provided

test/index.js
CircleCI started returning a valid 200 for bad URLs under the guise of DOS protection.  This change enforces bad domains during testing.
=> swapping test URLs to use .tld

lib/actions.js, test/index.js
Gives more helpful errors when using `.click`, `.mousedown` or `.mouseover`, and the selector cannot be found.
e.g. when running `.click('a.not-here')` and the element cannot be found, it will give back the error "Unable to find element by selector: a.not-here" instead of the previous "Cannot read property 'dispatchEvent' of null".
=> Give better error messages when element isn't found

Readme.md, lib/runner.js, test/index.js
Fixes two problems: one, if the name is not specified, clear all cookies for the current domain (#202); and two, return if there are no cookies specified to clear.  (This is a nascent bug that would cause Nightmare to hang indefinitely.)
I didn't change the cookie methods to look at an optional domain as I _think_ that's a bit outside the scope of this PR.  Should that be opened up in a separate issue, or should I include that here?
FWIW, the required changes:
* change `assign` to use `defaults` in `get ` and `set`
* alter `clear` to accept strings _or_ cookie objects with a a default URL to the current URL
=> clear all cookies

lib/runner.js
Fixes #350:  Ensures extra event listeners are removed when done/error is called, also allows for >1 log event per `javascript` call.
All credit should go to @s0m3on3 for the original fix.
(Also, I _thought_ this had already been submitted, but I can't find the original.)
=> patching javascript action to remove extra listeners

lib/runner.js
The fix for this bug in Electron was released with version 0.37.7 and we currently depend on `^0.37.7` so this should be safe to remove.
=> Remove workaround for older version of electron

lib/actions.js, lib/nightmare.js, test/index.js
This is a pass at moving the Nightmare start to the queue.  This removes the need for `.ready()`.  Also, this changeset makes the ending of an instance asynchronous.  (This props up downstream usability for #502 and possibly #598.)
=> moves electron start to Nightmare queue

.gitignore, lib/runner.js, test/index.js, test/server.js
Hi guys!
How about "Referer" header?
Usage:
```javascript
const url = 'https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending';
var nightmare = new Nightmare();
yield nightmare
.viewport(1920, 1080)
.goto(url, {
'Referer': 'http://my-referer.tld/'
})
.wait('body')
.screenshot(path.join(__dirname, 'referer.png'))
.end()
;
```
Result:
=> Add 'Referer' header support

lib/runner.js
closes https://github.com/segmentio/nightmare/issues/469
I've tested my tests with `0` timeout on the `.type()` function and can't report any keystrokes being emitted in the wrong order. 
Using the `setTimeout(fn, 0);` hack to defer the event to the next event loop of JavaScript should be just fine. 
I was tempted to make this timeout a configurable variable to aid debugging without making test suites run longer than necessary, but I did not want to introduce a breaking change.
=> Speed up `.type()` event

Readme.md
Based on several prior conversations toward moving Nightmare to a `.then()` based API, Nightmare has been updated to reflect that, but the readme has not been as well kept.
=> Remove yield from readme

Readme.md, lib/nightmare.js, lib/runner.js, test/fixtures/navigation/index.html, test/index.js, test/server.js
Fixes #689.
- moves timeout defaults to parent process
- adds a non-ending route to the test server
- uses `did-stop-loading` instead of `did-finish-loading` as the former
is called regardless of load success or not
- adds an optional page transition timeout called `loadTimeout` that
forces the `webContents` to stop after a given time.
=> open server connection load timeout

History.md, package.json, test/index.js
Fixes #694, also removes an errant `.only()` in the test suite.
=> update electron-prebuilt version

Readme.md
If the page load fails, the error will be an object **wit** the following properties
=> fix typo in Readme: wit to with

Readme.md
- fix link to contents.openDevTools function
- fix misspelling of 'detach'
- specify that 'detach' must be the value of the 'mode' property (see electron doc for confirmation)
=> fixes for openDevTools option

lib/nightmare.js, test/index.js
Addresses issue #704, also removes "it.only" from unit tests (assuming that was unintentional).
I admit that I'm not sure what to write for a unit test here.  If you can give me some guidance, that would great.  Otherwise, existing tests pass, and a test run on my machine appears to use the TZ environment variable.  Thanks!
=> Run it.only, and add option to provide env vars to electron process

circle.yml, lib/runner.js
Builds for #746 were failing in CI—it turns out this is because JSON serialization is failing from circular references. This is not the first time we’ve seen exceptions on serializing the raw event data, so I’m opting for just removing it altogether here. There’s very little meaningful information that actually comes with them to begin with.
=> Stop sending electron event data in forwarded events.

Readme.md, lib/nightmare.js, lib/runner.js, test/index.js, test/server.js
Fix #696.
Changes:
1. Adds error when authentication fails
1. Adds the ability to end a Nightmare chain from an event that happens out-of-band using the `die` event
1. Allows for credentials to be reset mid-stream.
=> error on bad authentication

Readme.md, lib/nightmare.js, lib/runner.js
Backs out #677 in favor of making the type interval an option.
=> making the `.type()` interval an option

circle.yml, lib/runner.js, test/index.js, test/server.js
This fixes #740. We used to only listed for `did-fail-load` events to signal failure because they were always emitted in any kind of failure. In Electron v1.2.6, some kinds of provisional failures stopped emitting `did-fail-load`, so we now also need to listen for `did-fail-provisional-load`.
=> Listen explicitly for provisional load failures in `goto`

lib/nightmare.js, lib/runner.js
Still not sure what exactly is causing the problem but it seams when you kill() the process is not giving time to electron.app to quit gracefully and that is not allowing the cookies/session to be saved. 
More info can be found here: [Quit gracefully when Ctrl-C is pressed in console #5273](https://github.com/electron/electron/issues/5273)
Fixes bug:
[Nightmare persist partition on windows bug #755](https://github.com/segmentio/nightmare/issues/755) 
Probable fix for:
[Always fail to set cookie #531](https://github.com/segmentio/nightmare/issues/531) 
[sharing a session between different machines? #398](https://github.com/segmentio/nightmare/issues/398)
[Sessions are not persisting in Ubuntu #536](https://github.com/segmentio/nightmare/issues/536)
=> Quit electron app gracefully instead of killing the process

lib/actions.js, test/fixtures/manipulation/index.html, test/index.js
If the element being typed or inserted into is removed from the DOM before the blur call is made (which can happen if the element is removed on a key event), an exception is raised.  `blurSelector` now makes sure the element still exists before making the blur call.  Also added a debug message if the selector does not exist after focusing.
Partially fixes #762.
=> Make blur optional for type and insert

Readme.md, lib/actions.js, lib/javascript.js, lib/nightmare.js, test/index.js
This PR is intended to let you run `.evaluate()`d functions that are asynchronous, either with callbacks or with promises.  For callbacks, if the `.evaluate()`d function's arity is one less than the passed in parameters, it'll assume the last argument to the function is the callback.  If the return value is a `then`able, it'll call `then()` to wait for promise fulfillment.  Otherwise, the call will behave synchronously as it does now.
This change is _potentially_ breaking as it does change behavior based on the arguments to `.evaluate()`.  Is this change worth the risk of possibly breaking implementations that already exist?
Related to #573 and closes #552.
=> asynchronous evaluate

lib/javascript.js, lib/nightmare.js, lib/runner.js, test/fixtures/manipulation/index.html, test/index.js
Fixes #839, cleaning up `evaluate_now` arguments and adding some tests to make sure that attribute selectors work as well as preventing inadvertent injection with `.click()`.
=> resolved arguments, added injection check

Readme.md, lib/actions.js, test/index.js
Fixes #901 
In my understanding, all exported actions are bound to the nightmare object on instantiate. So this will work fine.
```js
yield nightmare.goto('https://some.tld/path/is/here').path(); // outputs /path/is/here
```
=> Adds .path() to get path exclusively, instead of full url

Readme.md
I found two missing characters within the code example for the newly added Promises within an evaluate section.
Also, I removed done because including an extra parameter when using evaluate Promises will cause it to not work as a Promise and instead as a callback.
=> code example corrections

Readme.md, lib/nightmare.js, test/index.js
The current behavior uses electron default, which creates a partition
for storage which persists between instances. This makes sense for
electron but not necessarily for primary use cases of Nightmare.
This change sets the default partition to be a non-persistent partition
but allows a user to opt back into persistence with simple configuration options.
Fixes segmentio/nightmare#916
=> Alter default behavior to non-persistent partition

lib/preload.js, test/fixtures/unload/add-event-listener.html, test/fixtures/unload/index.html, test/index.js
Earlier today I ran into this issue: https://github.com/segmentio/nightmare/issues/824
I resolved it by creating a modified `preload.js` that prevents the browser from setting any `unload` or `beforeunload` handlers. This pull request includes my modified `preload.js` along with two tests that ensure that it works.
=> Prevent unload dialogs (...from preventing .end())

Readme.md
I have updated the link to the electron documentation to match the version that is specified in [package.json](https://github.com/segmentio/nightmare/blob/master/package.json) file.
This is relevant since the electron 1.4.4 documentation describes the option of specifying a custom page size when generating PDF-files.
=> Updated link to electron documentation

lib/nightmare.js, lib/runner.js
Makes it possible to listen for `media-started-playing` and `media-paused` with the on method.
Useful in testing apps that deal with audio playback.
=> Expose media playback events

lib/frame-manager.js
Since the initial implementation of `FrameManager`, Electron has added an API for Chromium's remote debugging protocol, which can visually highlight a portion of the page. This change uses that functionality to force a new frame to be rendered, which is much more reliable than the way Nightmare currently tries to force new frames to render by fiddling around with the DOM (see people experiencing problems with this in #555, #736, #809). It also has the benefit of not doing anything page content can observe, ensuring that any JS or CSS won't modify the page in response to Nightmare's attempt to take a screenshot.
This also adds a timeout. We should never hit it when using the debugger, but I figure it’s better to be safe than sorry here, especially after the hangs people have been …
=> Use debugger highlighting for triggering frames to render (improves screenshots)

Readme.md
I noticed this issue while reading the docs
=> Remove redundant docs for 'log' event from README

Readme.md, lib/nightmare.js, package.json, test/index.js
Native ES6 Promises are nice, but libraries like [Bluebird](npmjs.com/package/bluebird) offer a lot of nice additional features. I'd like to be able to specify which Promise library/factory nightmare uses internally to wrap return values from `.then()` and `.catch()` *(inspired by [mongoose.Promise](http://mongoosejs.com/docs/promises.html#plugging-in-your-own-promises-library))*
```js
import Nightmare from 'nightmare';
import Promise from 'bluebird';
class MyCrawler {
nightmare = null;
// PRIVATE
_authPromise = null;
constructor() {
this.nightmare = Nightmare();
}
async authenticate() {
if (this._authPromise && !this._authPromise.isFulfilled()) {
return await this._authPromise();
} else {
return await (this._authPromise = Promise.resolve(this.nightmare.goto('...').then()));
}
}
}
```
The …
=> Override nightmare `Promise` library

circle.yml
Rather than having to grant folks permissions, let's just let CI handle the `npm publish` stuff.
I've added our [Segment's] default npm key as an env var, so everything should Just Work™
=> circle: auto-publish to npm on semver-ish tags

Readme.md
Because Nightmarejs is built on top of electron, it's possible
to execute arbitrary code if a malicious website is loaded.
Electron provides a README that explicitly states that the code
you load is your responsibility, and so Nightmare must inherit
this principle.
=> Electron is unsafe to load malicious code in.

lib/frame-manager.js, package.json, test/index.js
I'm a new user of Nightmare but found an issue when recording multiple screenshots on a static page (i.e. one with no frame updates). I was recording multiple screenshots in series at different viewport sizes.
- Nightmare was hanging indefinitely when hidden
- Nightmare was hanging when visible until I moved my mouse over the content (thus generating a new frame for the debugger)
After some sleuthing, it looks like FrameManager has some sneaky edge cases that needed deeper testing. In this PR:
- Fixed up double subscription issue due to still using `subscribed` boolean despite no longer being used
- Added `requestedFrame` resetting on `attach` error and `timeout` so future attach errors/timeouts can get the same `null` frame
- Added tests
**Notes:**
With respect to tests, I feel like I …
=> Repaired support for multiple timeouts in FrameManager

lib/nightmare.js
I am not good at English, so I use Google translation.
I ran the following code to get cookies for all URLs.
However, it was output as `error: {}` and it did not work.
I investigated and corrected this cause.
If this committed change is correct, please merge.
```js
var Nightmare = require('nightmare');
// Get cookies for all URL
Nightmare.action('cookies', {
getAll: function (name, options, parent, win, renderer, done) {
parent.respondTo('cookie.getAll', function (done) {
win.webContents.session.cookies.get({}, function (err, cookies) {
if (err) {
return done(err);
}
done(null, cookies);
});
});
done();
}
},{
getAll: function (done) {
this.child.call('cookie.getAll', done);
}
});
var nightmare = Nightmare({show: true});
nightmare …
```
=> fix problems that are rejected when adding child actions with objects.

Readme.md, lib/actions.js, test/fixtures/manipulation/index.html, test/index.js
Particularly useful if invoking multiple `mouseover`s over objects and you want to take a screenshot of each in isolation e.g. tooltips, control hover states etc.
Currently a subsequent `mouseover` does not trigger a `mouseout` on an element that has previously been hovered over causing multiple hovered items to appear at once.  This at least provides low level support to programmatically dismiss those previously hovered items.
=> Add mouseout action to complement mouseover

package.json
This pins the version of Electron used by the project, to prevent issues with the nuked Electron 1.8.0 version (https://github.com/electron/electron/issues/10574#issuecomment-331373344).
This addresses: https://github.com/segmentio/nightmare/issues/1269
=> Pin Electron version

package.json
Updating electron version to 1.7.11 to resolve the critical severity security vulnerability in version range >= 1.7.0,< 1.7.11
cf. [CVE-2018-1000006](https://electronjs.org/blog/protocol-handler-fix)
=> Update electron version to 1.7.11 to fix CVE-2018-1000006

Readme.md, lib/nightmare.js, lib/runner.js, package.json
I could not find any simple way to access the `select-client-certificate` event on the electron instance via nightmare. This change will allow a nightmare user to select a client certificate by subjectName instead of always relying on the first available client certificate.
=> Added ability to specify the client certificate selected by electron

Readme.md
The example in `Readme.md` does not use `mocha-generators`.
=> Fix Readme.md

Readme.md, lib/javascript.js, lib/nightmare.js, lib/preload.js, test/fixtures/preload/index.js, test/fixtures/security/index.html, test/index.js
This is a **BREAKING** change.
This PR greatly restricts access to the IPC. The preload no longer exposes the IPC via `window.__nightmare.ipc`. Instead the IPC is wrapped in a send method that is not accessible to the page. 
Also since the preload script loads first, there's no opportunity for a malicious website to monkey-path that `send(event, data)` method.
For `.evaluate(src)` and `inject(...)`, we do need to be able to access the IPC from the window. For these cases, I've created dedicated methods that only allow the sending of a `response` and `error` event. We should be able to remove this altogether via https://github.com/segmentio/nightmare/issues/1387 but that's out of the scope of this PR.
This PR does break certain types of custom actions that relied on setting up custom …
=> refactor: remove window.__nightmare.ipc

Readme.md, lib/ipc.js, lib/javascript.js, lib/nightmare.js, lib/preload.js, lib/runner.js, test/fixtures/preload/index.js, test/fixtures/security/index.html, test/index.js
This is a **BREAKING** change and builds upon this PR #1390.
This PR fixes #646 and cleans up some of the adhoc error handling we've been doing.
I've chosen to add error serialization & unserialization at the IPC-level. This makes the IPC more opinionated (errors must always come first), but it allows us to transport errors across processes gracefully. Since nightmare already considered errors as the first argument everywhere, I didn't have to change much.
In addition to #1390, this is a breaking change because now promises that are rejected will always return `Error` types, whereas before sometimes we were returning objects, sometimes strings, sometimes `{}`. This is a minor breaking change, but warrants the `3.0.0` bump.
=> fix: properly serialize & unserialize errors across processes

lib/runner.js, package.json, test/index.js
Chromium before 2.0.18 is affected by this "Use-after-free in FileReader"
vulnerability, Google is aware of reports that an exploit for CVE-2019-5786
exists in the wild: https://electronjs.org/blog/filereader-fix
This vulnerability has high impact (CVSS3 Base Score 8.8).
Solution: Bump Nightmare's Electron dependency to version 2.0.18.
This pull request includes #1466
"Bumps the version of electron to 2.0.2" from ZackNeyland.
=>  Electron 2.0.18 - Chromium FileReader Vulnerability Fix (CVE-2019-5786)

lib/runner.js, package.json, test/index.js
With the version bump of electron it introduces some breaking API changes, those were fixed up. Also adjusted the tests a bit to handle the CSP as well as some oddities with the image comparison for the idle case (about:blank w/ a background color change).
This also addresses issues with 1.8+ not working on RaspberryPi. Seems that whatever was done in the builds on electron prior to 2.0.2 seems resolved now for armv7l.
=> Bumps the version of electron to 2.0.2
